spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}/${DB_NAME:testdb} # Dummy values
    username: ${DB_USERNAME:testuser} # Dummy username
    password: ${DB_PASSWORD:testpassword} # Dummy password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

# AWS Cloud Configuration
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:dummy-access-key} # Dummy AWS access key
      secret-key: ${AWS_SECRET_ACCESS_KEY:dummy-secret-key} # Dummy AWS secret key
    region:
      static: ${AWS_DEFAULT_REGION:us-east-1} # Dummy AWS region
    stack:
      auto: false

server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:${KEY_STORE_PATH:/dummy/keystore.p12} # Dummy key store path
    key-store-password: ${KEYSTORE_PASSWORD:dummy-keystore-password} # Dummy key store password
    key-store-type: PKCS12
    key-alias: ssl-cert

bucket:
  name: contactless-checking # Dummy bucket name

jwt:
  signerKey: ${JWT_KEY:dummy-jwt-key} # Dummy JWT signer key