# Get the ENV from k8s, docker env
logging:
  level:
    org:
      springframework:
        web: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  # Actuator configuration
  management:
    endpoints:
      web:
        exposure:
          include: "health"
    endpoint:
      health:
        show-details: "always"
    health:
      db:
        enabled: true

# AWS Cloud Configuration
cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    region:
      static: us-east-1
    stack:
      auto: false

server:
  port: 8080

bucket:
  name: contactless-checking

cors:
  allowed-origins: http://localhost, http://127.0.0.1