spring.datasource.url = jdbc:mysql://172.17.0.3/checking
spring.datasource.username = checking
spring.datasource.password = checking
spring.datasource.driver-class-name = com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
