# MySQL Secret Key
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ck-mysql.name" . }}-secret
type: Opaque
{{ include "ck-mysql.secrets" . }}
---
# Server Opaque Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ck-authentication.name" . }}-secret
type: Opaque
{{ include "ck-authentication.secrets" . }}
---
# TLS Server TLS Secret
apiVersion: v1
kind: Secret
metadata:
  name: ca-cert
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/ca.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/ca.key" | b64enc }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ck-app-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: tls-cert
  duration: 2160h
  renewBefore: 360h
  commonName: ck-application
  dnsNames:
    - {{ template "ck-authentication.name" . }}
    - {{ template "ck-server.name" . }}
  ipAddresses:
    {{- include "ck-application.ipAddress" . }}
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io