apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-authentication.name" . }}
spec:
  selector:
    app: {{ template "ck-authentication.name" . }}
  ports:
    - name: {{ template "ck-authentication.name" . }}-http
      protocol: "TCP"
      port: {{ .Values.server.authentication.port }}
      targetPort: http-auth-svc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-server.name" . }}
spec:
  selector:
    app: {{ template "ck-server.name" . }}
  ports:
    - name: {{ template "ck-server.name" . }}-http
      protocol: TCP
      port: {{ .Values.server.faceModel.port }}
      targetPort: http-server-svc
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-client.name" . }}-http
spec:
  selector:
    app: {{ template "ck-client.name" . }}
  ports:
    - name: {{ template "ck-client.name" . }}-http
      protocol: TCP
      port: {{ .Values.server.faceClient.httpPort }}
      targetPort: http-client-svc
  type: ClusterIP
