{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ck-client.name" . }}-ingress
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ include "ck-application.ingressPath" (list . (include "ck-client.name" . )) }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ck-client.name" . }}-http
            port:
              number: {{ .Values.server.faceClient.httpPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ck-authentication.name" . }}-ingress
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ include "ck-application.ingressPath" (list . (include "ck-authentication.name" . )) }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ck-authentication.name" . }}
            port:
              number: {{ .Values.server.authentication.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ck-server.name" . }}-ingress
spec:
  ingressClassName: "nginx"
  rules:
  - host: {{ include "ck-application.ingressPath" (list . (include "ck-server.name" . )) }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "ck-server.name" . }}
            port:
              number: {{ .Values.server.faceModel.port }}              
{{- end }}
