apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-authentication.name" . }}
spec:
  selector:
    app: {{ template "ck-authentication.name" . }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.server.authentication.port }}
      targetPort: {{ .Values.server.authentication.port }}
      nodePort: {{ .Values.server.authentication.nodePort }} # Assign static NodePort
      name: {{ template "ck-authentication.name" . }}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-server.name" . }}
spec:
  selector:
    app: {{ template "ck-server.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.server.faceModel.port }}
      nodePort: {{ .Values.server.faceModel.nodePort }} # Assign static NodePort
      targetPort: {{ .Values.server.faceModel.port }}
      name: {{ template "ck-server.name" . }}
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-client.name" . }}
spec:
  selector:
    app: {{ template "ck-client.name" . }}
  ports:
    - name: {{ template "ck-client.name" . }}
      protocol: TCP
      port: {{ .Values.server.faceClient.port }}
      # nodePort: {{ .Values.server.faceClient.nodePort }} # Assign static NodePort
      targetPort: {{ .Values.server.faceClient.port }}
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  loadBalancerIP: {{ .Values.server.externalIP }}