# MySQL Secret Key
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ck-mysql.name" . }}-secret
type: Opaque
{{ include "ck-mysql.secrets" . }}
---
# Server Opaque Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ck-authentication.name" . }}-secret
type: Opaque
{{ include "ck-authentication.secrets" . }}