apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ck-authentication.name" . }}-configmap
  labels: 
    {{- include "ck-authentication.labels" . | nindent 4 }}
  annotations: 
    {{- include "ck-application.annotations" . | nindent 4 }}
data:
  application.yaml: |
{{ tpl (.Files.Get "files/application.yaml") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ck-mysql.name" . }}-configmap
data:
  primary.cnf: |
    [mysqld]
    log-bin
  replica.cnf: |
    [mysqld]
    super-read-only
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ck-client.name" . }}-configmap
  labels: 
    {{- include "ck-client.labels" . | nindent 4 }}
  annotations: 
    {{- include "ck-application.annotations" . | nindent 4 }}
data:
  default.conf: |
{{ tpl (.Files.Get "files/default_conf.yaml") . | indent 4 }}