apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-authentication.name" . }}
spec:
  selector:
    app: {{ template "ck-authentication.name" . }}
  ports:
    - name: {{ template "ck-authentication.name" . }}-http
      protocol: "TCP"
      port: {{ .Values.server.authentication.port }}
      targetPort: https-auth-svc
      nodePort: {{ .Values.server.authentication.nodePort }} # Assign static NodePort
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-server.name" . }}
spec:
  selector:
    app: {{ template "ck-server.name" . }}
  ports:
    - name: {{ template "ck-server.name" . }}-http
      protocol: TCP
      port: {{ .Values.server.faceModel.port }}
      nodePort: {{ .Values.server.faceModel.nodePort }} # Assign static NodePort
      targetPort: http-server-svc
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-client.name" . }}-http
spec:
  selector:
    app: {{ template "ck-client.name" . }}
  ports:
    - name: {{ template "ck-client.name" . }}-http
      protocol: TCP
      port: {{ .Values.server.faceClient.httpPort }}
      nodePort: {{ .Values.server.faceClient.httpNodePort }} # Assign static NodePort
      targetPort: http-client-svc
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-client.name" . }}-https
spec:
  selector:
    app: {{ template "ck-client.name" . }}
  ports:
    - name: {{ template "ck-client.name" . }}-https
      protocol: TCP
      port: {{ .Values.server.faceClient.tlsPort }}
      nodePort: {{ .Values.server.faceClient.tlsNodePort }} # Assign static NodePort
      targetPort: tls-client-svc
  type: NodePort