apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ template "ck-server.name" . }}-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    ingressClassName: nginx
    rules:
    - host: {{ .Release.Namespace }}.ck-server.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ template "ck-server.name". }}
              port:
                number: {{ int (.Values.server.socketServer.port) }}