apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-authentication.name" . }}
spec:
  selector:
    app: {{ template "ck-authentication.name" . }}
  ports:
    - name: {{ template "ck-authentication.name" . }}-http
      protocol: "TCP"
      port: {{ .Values.server.authentication.port }}
      {{- if not (eq .Values.server.authentication.serviceType "ClusterIP" ) }}
      nodePort: {{ .Values.server.authentication.nodePort }}
      {{- end }}
      targetPort: http-auth-svc
  type: {{ .Values.server.authentication.serviceType }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-server.name" . }}
spec:
  selector:
    app: {{ template "ck-server.name" . }}
  ports:
    - name: {{ template "ck-server.name" . }}-http
      protocol: TCP
      port: {{ .Values.server.faceModel.port }}
      {{- if not (eq .Values.server.faceModel.serviceType "ClusterIP" ) }}
      nodePort: {{ .Values.server.faceModel.nodePort }}
      {{- end }}
      targetPort: http-server-svc
  type: {{ .Values.server.faceModel.serviceType }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-client.name" . }}-http
spec:
  selector:
    app: {{ template "ck-client.name" . }}
  ports:
    - name: {{ template "ck-client.name" . }}-http
      protocol: TCP
      port: {{ .Values.server.faceClient.httpPort }}
      {{- if not (eq .Values.server.faceClient.serviceType "ClusterIP" ) }}
      nodePort: {{ .Values.server.faceClient.httpNodePort }}
      {{- end }}
      targetPort: http-client-svc
  type: {{ .Values.server.faceClient.serviceType }}
