apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-authentication.name" . }}
spec:
  selector:
    app: {{ template "ck-authentication.name" . }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.server.authentication.port }}
      targetPort: {{ .Values.server.authentication.port }}
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-server.name" . }}
spec:
  selector:
    app: {{ template "ck-server.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.server.faceModel.port }}
      targetPort: {{ .Values.server.faceModel.port }}
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-client.name" . }}
spec:
  selector:
    app: {{ template "ck-client.name" . }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.server.faceClient.port }}
      targetPort: {{ .Values.server.faceClient.port }}
  externalTrafficPolicy: Local
  type: LoadBalancer
