apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-authentication.name" . }}
spec:
  selector:
    app: {{ template "ck-authentication.name" . }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.server.authentication.port }}
      targetPort: {{ .Values.server.authentication.port }}
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-server.name" . }}
spec:
  selector:
    app: {{ template "ck-server.name" . }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.server.faceModel.port }}
      targetPort: {{ .Values.server.faceModel.port }}
      nodePort: {{ .Values.server.faceModel.nodePort | default "32500" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ck-client.name" . }}
spec:
  selector:
    app: {{ template "ck-client.name" . }}
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.server.faceClient.port }}
      targetPort: {{ .Values.server.faceClient.port }}
      nodePort: {{ .Values.server.faceClient.nodePort | default "32080" }}
