apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ck-authentication.name" . }}
  labels: 
    {{- include "ck-authentication.labels" . | nindent 4 }}
  annotations: 
    {{- include "ck-application.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  strategy:
    {{ toYaml .Values.updateStrategy | indent 4 }}
  selector:
    matchLabels: 
      {{- include "ck-authentication.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: 
        {{- include "ck-application.annotations" . | nindent 8 }}
      labels: 
        {{- include "ck-authentication.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: {{ template "ck-application.fsGroup.coordinated" . }}
        {{- include "ck-application.podSeccompProfile" . | indent 8 }}
        {{- include "ck-application.supplementalGroups" . }}
      initContainers:
        - name: wait-for-mysql
          image: {{ template "ck-application.imagePath" (merge (dict "imageName" "ck-mysql") .) }}
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ template "ck-mysql.name" . }}-secret
                  key: {{ template "ck-mysql.name" . }}-host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "ck-mysql.name" . }}-secret
                  key: {{ template "ck-mysql.name" . }}-dbName
            - name: DB_USERNAME
              {{- if not (eq ((include "ck-mysql.password" .) | b64dec) "root") }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "ck-mysql.name" . }}-secret
                  key: {{ template "ck-mysql.name" . }}-user
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "ck-mysql.name" . }}-secret
                  key: {{ template "ck-mysql.name" . }}-root-password
              {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "ck-mysql.name" . }}-secret
                  key: {{ template "ck-mysql.name" . }}-password
          command:
            - sh
            - -c
            - |
              echo "Starting initContainer to wait for MySQL";
              until mysql -h $DB_HOST -u $DB_USERNAME -p$DB_PASSWORD -e "SELECT 1"; do
                echo "Waiting for MySQL to be ready...";
                sleep 5;
              done;
              echo "MySQL is up and running";
              echo "Init container finished successfully";
      containers:
        {{- include "ck-auth-containers" (list .) | nindent 6 }}