{{- $g := fromJson (include "ck-application.global" . ) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ck-authentication.name" . }}
  labels: 
    {{- include "ck-authentication.labels" . | nindent 4 }}
  annotations: 
    {{- include "ck-application.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  strategy:
    {{ toYaml .Values.updateStrategy | indent 4 }}
  selector:
    matchLabels: 
      {{- include "ck-authentication.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: 
        {{- include "ck-application.annotations" . | nindent 8 }}
      labels: 
        {{- include "ck-authentication.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- include "ck-application.appArmorProfile.securityContext" (list .) | indent 8 }}
        fsGroup: {{ template "ck-application.fsGroup.coordinated" . }}
        {{- include "ck-application.podSeccompProfile" . | indent 8 }}
        {{- include "ck-application.supplementalGroups" . }}
      initContainers:
      {{- include "ck-initContainers" (list . "authentication") | indent 6 }}
      containers:
      {{- include "ck-auth-containers" (list .) | nindent 6 }}