{{- if .Values.storage.persistentVolume.enabled }}
{{- $namespace := include "ck-application.namespace" . -}}
{{- $storageClassName := printf "%s-%s" $namespace .Values.storage.storageClass.name -}}

# StorageClass Definition
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ $storageClassName }}
provisioner: {{ .Values.storage.storageClass.provisioner }}
volumeBindingMode: WaitForFirstConsumer
---
# PersistentVolume and PersistentVolumeClaim for MySQL
{{- $mysqlName := include "ck-mysql.name" . -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $mysqlName }}-pv-volume-ck
  labels:
    app: {{ $mysqlName }}
spec:
  storageClassName: {{ $storageClassName }}
  capacity:
    storage: {{ .Values.storage.persistentVolume.storageCapacity.mysql }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage.persistentVolume.hostPath.mysql }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $mysqlName }}-pv-claim
  labels:
    app: {{ $mysqlName }}
    tier: database
spec:
  storageClassName: {{ $storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.persistentVolume.storageCapacity.mysql }}
---
# PersistentVolume and PersistentVolumeClaim for Server
{{- $serverName := include "ck-server.name" . -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $serverName }}-pv-volume-ck
  labels:
    app: {{ $serverName }}
spec:
  storageClassName: {{ $storageClassName }}
  capacity:
    storage: {{ .Values.storage.persistentVolume.storageCapacity.server }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage.persistentVolume.hostPath.server }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $serverName }}-pv-claim
  labels:
    app: {{ $serverName }}
spec:
  storageClassName: {{ $storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.persistentVolume.storageCapacity.server }}
{{- end }}
