apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "ck-mysql.name" . }}-pv-volume-ck
  labels:
    type: local
spec:
  storageClassName: {{ .Values.storageClassName }}
  capacity:
    storage: {{ .Values.storageCapacity.mysql }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/ck/data-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "ck-mysql.name" . }}-pv-claim
  labels:
    app: {{ template "ck-mysql.name" .}}
    tier: database
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageRequest.mysql }}