apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ck-client.name" . }}
  labels: {{- include "ck-client.labels" . | nindent 4 }}
  annotations: {{- include "ck-application.annotations" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  strategy:
{{ toYaml .Values.updateStrategy | indent 4 }}
  selector:
    matchLabels: {{- include "ck-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {{- include "ck-application.annotations" . | nindent 8 }}
      labels: {{- include "ck-client.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- include "ck-application.appArmorProfile.securityContext" (list .) | indent 8 }}
        fsGroup: {{ template "ck-application.fsGroup.coordinated" . }}
        {{- include "ck-application.podSeccompProfile" . | indent 8 }}
        {{- include "ck-application.supplementalGroups" . }}
      containers:
      {{- include "ck-client-containers" (list .) | nindent 6 }}
