apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: Y2hlY2tpbmc=
  mysql-password: Y2hlY2tpbmc=
  mysql-user: Y2hlY2tpbmc=
  mysql-host: Y2hlY2tpbmc=
  mysql-dbName: Y2hlY2tpbmc=
