---
# TLS Server TLS Secret
apiVersion: v1
kind: Secret
metadata:
  name: ca-cert
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "files/ca.crt" | b64enc }}
  tls.key: {{ .Files.Get "files/ca.key" | b64enc }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ck-app-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: tls-cert
  duration: 2160h
  renewBefore: 360h
  commonName: ck-application
  dnsNames:
    - ck-application-authentication
    - ck-application-authentication.{{ .Release.Namespace }}
    - ck-application-authentication.{{ .Release.Namespace }}.svc
    - ck-application-authentication.{{ .Release.Namespace }}.svc.cluster.local
    - ck-application-server
    - ck-application-server.{{ .Release.Namespace }}
    - ck-application-server.{{ .Release.Namespace }}.svc
    - ck-application-server.{{ .Release.Namespace }}.svc.cluster.local
  ipAddresses:
    - 192.168.122.70
    - 192.168.122.65
    - 192.168.122.64
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io