productName: Contactless Checking Monitoring System
images:
  ck-xtrabackup:
    productName: CK XtraBackup IMAGE
    registry: gcr.io/google-samples
    name: xtrabackup
    tag: "1.0"
  ck-authentication:
    productName: CK Authentication API server
    registry: '%%REGISTRY%%'
    name: ck-authentication
    tag: '%%VERSION%%'
  ck-face-model:
    productName: CK Face Model server
    registry: '%%REGISTRY%%'
    name: ck-face_model
    tag: '%%VERSION%%'
  ck-face-client:
    productName: CK Face Web Client
    registry: '%%REGISTRY%%'
    name: ck-face_client
    tag: '%%VERSION%%'