#global:
# security:
#   tls:
#     enabled: true
# registry:
#   url: anhdung12399
#   repoPath:
# timezone: UTC
# nodeSelector: {}
# annotations: {}
# labels: {}
# networkPolicy:
#   enabled:z
# topologySpreadConstraints:
# podSecurityContext:
#   supplementalGroups: []
# fsGroup:
#   # 'manual' to enforce a specific value (highest precedence)
#   manual:
#   # 'namespace' to use the value defined for the namespace set by cluster admin (second highest precedence)
#   namespace:

updateStrategy:
  type: RollingUpdate

server:
  replicaCount: 1
  secretsPath:
    certPath: /run/secrets/tls
    keyStorePath: /run/secrets/keystore
  nodeIP: 192.168.122.65
  mysqlServer:
    name: mysql-server
    port: 3306
  xtrabackup:
    name: xtrabackup
    port: "3307"

  probes:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 3
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 20
      timeoutSeconds: 3
      successThreshold: 1
      failureThreshold: 5

  #serviceAccountName: ""
  authentication:
    name: authentication
    serviceType: LoadBalancer
    httpPort: "8080"
    httpsPort: "8443"
    httpNodePort: "30800"
    httpsNodePort: "30844"

  faceModel:
    name: face-model
    serviceType: LoadBalancer
    httpPort: "5000"
    httpsPort: "5443"
    httpNodePort: "30500"
    httpsNodePort: "30544"

  faceClient:
    name: face-client
    serviceType: LoadBalancer
    httpPort: "80"
    httpsPort: "443"
    httpNodePort: "31080"
    httpsNodePort: "31443"

resources:
  initcontainer:
    limits:
      cpu: "1"
      memory: "200Mi"
    requests:
      cpu: "50m"
      memory: "50Mi"
  xtrabackup:
    limits:
      cpu: "1"
      memory: "200Mi"
    requests:
      cpu: "50m"
      memory: "50Mi"
  mysql:
    limits:
      cpu: "2"
      memory: "2048Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  authentication:
    limits:
      cpu: "2"
      memory: "2048Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  face-model:
    limits:
      cpu: "4"
      memory: "4096Mi"
    requests:
      cpu: "2"
      memory: "2048Mi"
  face-client:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      requests: "100Mi"
    
annotations: {}

seccompProfile:
  type:
  # initcontainer:
  #   type:
  #   localhostProfile:
  # mysql:
  #   type:
  #   localhostProfile:
  # authentication:
  #   type:
  #   localhostProfile:
  # face-client:
  #   type:
  #   localhostProfile:
  # face-model:
  #   type:
  #   localhostProfile:

imageCredentials:
  pullPolicy: IfNotPresent

appArmorProfile:
  type: ""
  localhostProfile:
  authentication:
    type: ""
    localhostProfile:
  face-client:
    type: ""
    localhostProfile:
  face-model:
    type: ""
    localhostProfile:

storage:
  enabled: true
  persistentVolume:
    enabled: true
    hostPath:
      server: /mnt/ck/data-server
      mysql: /mnt/ck/data-mysql
      authentication: /mnt/ck/data-authentication
    storageCapacity:
      mysql: 30Gi
      server: 10Gi
      authentication: 1Gi
  storageClass:
    enabled: true
    name: local-storage
    provisioner: kubernetes.io/no-provisioner

password:
  dbPass: ""
  keystorePass: ""

ingress:
  enabled: false
  hostName: cluster-intern.site

aws:
  key:
  secret:
  region: us-east-1

issuer:
  ipAddress:
  - 192.168.122.70
  - 192.168.122.65
  - 192.168.122.64