#global:
# registry:
#   url: anhdung12399
#   repoPath:
# timezone: UTC
# nodeSelector: {}
# annotations: {}
# labels: {}
# networkPolicy:
#   enabled:
# topologySpreadConstraints:
# podSecurityContext:
#   supplementalGroups: []
# fsGroup:
#   # 'manual' to enforce a specific value (highest precedence)
#   manual:
#   # 'namespace' to use the value defined for the namespace set by cluster admin (second highest precedence)
#   namespace:

updateStrategy:
  type: RollingUpdate

server:
  replicaCount: 1
  mysqlServer:
    name: mysql-server
    port: 3306
  xtrabackup:
    name: xtrabackup
    port: "3307"

  #serviceAccountName: ""
  authentication:
    name: authentication
    serviceType: ClusterIP
    port: "8080"
    nodePort: "30800"
    probes:
      readiness:
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 3
      liveness:
        initialDelaySeconds: 15
        periodSeconds: 20
        timeoutSeconds: 3
        successThreshold: 1
        failureThreshold: 5

  faceModel:
    name: face-model
    serviceType: ClusterIP
    port: "5000"
    nodePort: "30500"

  faceClient:
    serviceAccountName: client-sa
    name: face-client
    serviceType: ClusterIP
    httpPort: "80"
    httpNodePort: "30080"

resources:
  initcontainer:
    limits:
      cpu: "1"
      memory: "200Mi"
    requests:
      cpu: "50m"
      memory: "50Mi"
  xtrabackup:
    limits:
      cpu: "1"
      memory: "200Mi"
    requests:
      cpu: "50m"
      memory: "50Mi"
  mysql:
    limits:
      cpu: "2"
      memory: "2048Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  authentication:
    limits:
      cpu: "2"
      memory: "2048Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  face-model:
    limits:
      cpu: "4"
      memory: "4096Mi"
    requests:
      cpu: "2"
      memory: "2048Mi"
  face-client:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      requests: "100Mi"
    
annotations: {}

seccompProfile:
  type:
  # ck-mysql:
  #   type:
  #   localhostProfile:
  # ck-authentication:
  #   type:
  #   localhostProfile:
  # ck-client:
  #   type:
  #   localhostProfile:
  # ck-socket-server:
  #   type:
  #   localhostProfile:

imageCredentials:
  pullPolicy: IfNotPresent

storageClassName: local-storage

storageCapacity:
  mysql: 10Gi
  server: 10Gi

storageRequest:
  mysql: 5Gi
  server: 5Gi

dbPass: ""

ingress:
  enabled: true
  hostName: cluster-intern.site

aws:
  key:
  secret:
  region: us-east-1

issuer:
  ipAddress:
  - 192.168.122.70
  - 192.168.122.65
  - 192.168.122.64