#global:
# registry:
#   url: anhdung12399
#   repoPath:
# timezone: UTC
# nodeSelector: {}
# annotations: {}
# labels: {}
# networkPolicy:
#   enabled:
# topologySpreadConstraints:
# podSecurityContext:
#   supplementalGroups: []
# fsGroup:
#   # 'manual' to enforce a specific value (highest precedence)
#   manual:
#   # 'namespace' to use the value defined for the namespace set by cluster admin (second highest precedence)
#   namespace:

updateStrategy:
  type: RollingUpdate

server:
  replicaCount: 1
  externalIP: 192.168.49.2
  mysqlServer:
    name: mysql-server
    port: 3306
  xtrabackup:
    name: xtrabackup
    port: "3307"

  #serviceAccountName: ""
  authentication:
    name: authentication
    port: "8080"
    nodePort: "30800"

  faceModel:
    name: face-model
    port: "5000"
    nodePort: "30500"

  faceClient:
    name: face-client
    port: "80"
    nodePort: "30080"

resources:
  initcontainer:
    limits:
      cpu: "1"
      memory: "200Mi"
    requests:
      cpu: "50m"
      memory: "50Mi"
  xtrabackup:
    limits:
      cpu: "1"
      memory: "200Mi"
    requests:
      cpu: "50m"
      memory: "50Mi"
  mysql:
    limits:
      cpu: "2"
      memory: "2048Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  authentication:
    limits:
      cpu: "2"
      memory: "2048Mi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  face-model:
    limits:
      cpu: "4"
      memory: "4096Mi"
    requests:
      cpu: "2"
      memory: "2048Mi"
  face-client:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      requests: "100Mi"
    
annotations: {}

seccompProfile:
  type:
  # ck-mysql:
  #   type:
  #   localhostProfile:
  # ck-authentication:
  #   type:
  #   localhostProfile:
  # ck-client:
  #   type:
  #   localhostProfile:
  # ck-socket-server:
  #   type:
  #   localhostProfile:

imageCredentials:
  pullPolicy: IfNotPresent

storageClassName:
  mysql: local-storage

storageCapacity:
  mysql: 10Gi

dbPass: ""

ingress:
  enabled: true